image:
  file: .gitpod.dockerfile
ports:
    - port: 8080
tasks:
    - name: Instalation
      init: >
      npm i -g heroku;
      cp jobcore/.env.example ../.env;
    - name: Terminal
      command: >
      virtualenv venv &&
      source venv/bin/activate