image:
  file: .gitpod.Dockerfile
ports:
    - port: 8080
    - port: 5432
tasks:
    - name: Instalation
      init: >
        npm i -g heroku;
        cp jobcore/.env.example jobcore/.env;
        virtualenv venv;
        source venv/bin/activate;
        pip3 install -r requirements.txt;
    - name: Terminal
      command: >
        npm i -g heroku;
        virtualenv venv;
        source venv/bin/activate;
        python3 manage.py runserver 8080;