image:
  file: .gitpod.Dockerfile
ports:
    - port: 8080
    - port: 5432
tasks:
    - name: Instalation
      init: >
        npm i -g heroku;
        cp jobcore/.env.example jobcore/.env;
        pipenv install;
    - name: Terminal
      command: >
        npm i -g heroku;