image:
  file: .gitpod.Dockerfile
ports:
    - port: 8080
    - port: 5432
tasks:
    - name: Instalation
      init: >
        cp jobcore/.env.example jobcore/.env;
    - name: Terminal
      command: >
        npm i -g heroku;
        pipenv install;
        psql -U gitpod -c 'CREATE DATABASE jobcore;';
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d jobcore;
        pipenv run migrate;
        pipenv run seed;
