version: '3'

services:
  db:
    image: postgres:11.7-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  web:
    build: .
    command: bash -c "sleep 1 && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - '.env.tests'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
