version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    env_file:
      - '.env.tests'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
