# Generated by Django 2.0 on 2018-07-17 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('image_url', models.TextField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.IntegerField(blank=True, default=0)),
                ('minimum_hourly_rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='api.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=30)),
                ('response_time', models.IntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='api.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(blank=True, to='api.Employee')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employer')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_restriction', models.CharField(blank=True, choices=[('FAVORITES', 'Favorites Only'), ('ANYONE', 'Anyone can apply')], default='ANYONE', max_length=9)),
                ('maximum_allowed_employees', models.IntegerField(blank=True, default=0)),
                ('minimum_hourly_rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('minimum_allowed_rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Receiving candidates'), ('FILLED', 'Filled'), ('PAUSED', 'Paused'), ('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=9)),
                ('date', models.DateTimeField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('finish_time', models.TimeField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_from_list', models.ManyToManyField(blank=True, to='api.FavoriteList')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('shift', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='candidates',
            field=models.ManyToManyField(blank=True, through='api.ShiftApplication', to='api.Employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='shift_accepted_employees', to='api.Employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='employer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employer'),
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='required_badges',
            field=models.ManyToManyField(blank=True, to='api.Badge'),
        ),
        migrations.AddField(
            model_name='shift',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Venue'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(blank=True, to='api.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
