# Generated by Django 2.0 on 2018-07-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobcoreinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelist',
            old_name='owner',
            new_name='employer',
        ),
    ]
