# Generated by Django 2.0 on 2018-07-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180727_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Pending'), ('APPLIED', 'Applied'), ('CANCELLED', 'Rejected')], default='DRAFT', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('shift', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shift')),
            ],
        ),
    ]
