# Generated by Django 2.0 on 2018-10-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181015_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='total_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
