# Generated by Django 2.0 on 2018-07-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shiftinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinvite',
            name='sender',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
