# Generated by Django 2.0 on 2018-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
