# Generated by Django 2.0 on 2018-08-20 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180820_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcoreinvite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='shift',
            name='application_restriction',
            field=models.CharField(blank=True, choices=[('FAVORITES', 'Favorites Only'), ('ANYONE', 'Anyone can apply'), ('SPECIFIC_PEOPLE', 'Specific People')], default='ANYONE', max_length=9),
        ),
    ]
