# Generated by Django 2.0 on 2018-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180820_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_tutorial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobcoreinvite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
