# Generated by Django 2.0 on 2018-11-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employer_automatically_accept_from_favlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='ending_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='starting_at',
            field=models.DateTimeField(),
        ),
    ]
