# Generated by Django 2.0 on 2018-11-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181114_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
