# Generated by Django 2.0 on 2018-09-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180824_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcoreinvite',
            name='shift',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Shift'),
        ),
        migrations.AddField(
            model_name='jobcoreinvite',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=9),
        ),
    ]
