# Generated by Django 2.0 on 2018-09-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180904_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcoreinvite',
            name='shift',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shift'),
        ),
    ]
