# Generated by Django 2.0 on 2018-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181129_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=9),
        ),
    ]
