# Generated by Django 2.0 on 2018-12-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clockin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='shift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shift'),
        ),
    ]
