# Generated by Django 2.0 on 2018-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180910_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SUSPENDED', 'Suspended'), ('PENDING_EMAIL_VALIDATION', 'PENDING_EMAIL_VALIDATION')], default='PENDING_EMAIL_VALIDATION', max_length=15),
        ),
    ]
