# Generated by Django 2.0 on 2018-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181210_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='comments',
            field=models.TextField(default='no comments'),
            preserve_default=False,
        ),
    ]
