# Generated by Django 2.0 on 2018-12-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rate_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='maximum_clockin_delta_minutes',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='maximum_clockout_delay_minutes',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
