# Generated by Django 2.0 on 2018-09-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180911_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcoreinvite',
            name='shift',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shift'),
        ),
    ]
