# Generated by Django 2.0 on 2018-09-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180911_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWeekAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='available_on_weekends',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='minimum_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AddField(
            model_name='employeeweekavailability',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
    ]
