# Generated by Django 2.0 on 2019-01-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181210_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='maximum_clockin_delta_minutes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='maximum_clockout_delay_minutes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='payroll_period_length',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AddField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='payroll_period_type',
            field=models.CharField(blank=True, choices=[('DAYS', 'Days'), ('MONTHS', 'Months')], default='DAYS', max_length=25),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=9),
        ),
    ]
