# Generated by Django 2.0 on 2018-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180912_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
