# Generated by Django 2.0 on 2019-01-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190107_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=9)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('employer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriodPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_hours', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('over_time', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
                ('paryroll_period', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.PayrollPeriod')),
                ('shift', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shift')),
            ],
        ),
    ]
