# Generated by Django 2.0 on 2018-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180912_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
