# Generated by Django 2.0 on 2019-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_payrollperiod_payrollperiodpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='employee',
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='length',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='length_type',
            field=models.CharField(blank=True, choices=[('DAYS', 'Days'), ('MONTHS', 'Months')], default='DAYS', max_length=25),
        ),
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='splited_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=9),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Finalized'), ('OPEN', 'Open')], default='OPEN', max_length=9),
        ),
    ]
