# Generated by Django 2.0 on 2018-09-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_position_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
