# Generated by Django 2.0 on 2019-01-10 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190110_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 0, 0, 0, 436129, tzinfo=utc)),
        ),
    ]
