# Generated by Django 2.0 on 2018-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_employee_job_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='application_restriction',
            field=models.CharField(blank=True, choices=[('FAVORITES', 'Favorites Only'), ('ANYONE', 'Anyone can apply'), ('SPECIFIC_PEOPLE', 'Specific People')], default='ANYONE', max_length=20),
        ),
    ]
