# Generated by Django 2.0 on 2019-01-22 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190111_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelist',
            name='auto_accept_employees_on_this_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 22, 0, 0, 0, 808654, tzinfo=utc)),
        ),
    ]
