# Generated by Django 2.0 on 2019-05-29 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190122_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='last_payment_period',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 0, 0, 0, 215303, tzinfo=utc)),
        ),
    ]
