# Generated by Django 2.0 on 2018-09-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180914_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftinvite',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('CANCELLED', 'Rejected')], default='PENDING', max_length=9),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street_address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
