# Generated by Django 2.0 on 2019-06-04 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190529_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 4, 0, 0, 0, 873023, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shiftinvite',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=9),
        ),
    ]
