# Generated by Django 2.0 on 2018-09-18 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_employee_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeWeekAvailability',
            new_name='EmployeeWeekUnvailability',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftinvite',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9),
        ),
    ]
