# Generated by Django 2.0 on 2019-06-06 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190604_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='employer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 6, 0, 0, 0, 161892, tzinfo=utc)),
        ),
    ]
