# Generated by Django 2.0 on 2018-09-20 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180918_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='date',
            new_name='ending_at',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='starting_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 20, 18, 38, 19, 576581, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
