# Generated by Django 2.0 on 2019-06-06 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190606_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollperiodpayment',
            old_name='paryroll_period',
            new_name='payroll_period',
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 6, 0, 0, 0, 831034, tzinfo=utc)),
        ),
    ]
