# Generated by Django 2.0 on 2018-09-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180920_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurrent', models.BooleanField(default=True)),
                ('allday', models.BooleanField(default=True)),
                ('recurrency_type', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=25)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeweekunvailability',
            name='employee',
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Receiving candidates'), ('FILLED', 'Filled'), ('PAUSED', 'Paused'), ('DRAFT', 'Draft'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=9),
        ),
        migrations.DeleteModel(
            name='EmployeeWeekUnvailability',
        ),
    ]
