# Generated by Django 2.2 on 2019-06-08 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190606_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_pending_payments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 8, 0, 0, 0, 235802, tzinfo=utc)),
        ),
    ]
