# Generated by Django 2.2 on 2019-06-10 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190610_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='picture',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 10, 0, 0, 0, 211660, tzinfo=utc)),
        ),
    ]
