# Generated by Django 2.0 on 2018-10-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180928_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='available_on_weekends',
        ),
        migrations.AddField(
            model_name='employee',
            name='maximum_job_distance_miles',
            field=models.IntegerField(default=50),
        ),
    ]
