# Generated by Django 2.2 on 2019-06-11 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190610_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 11, 0, 0, 0, 350703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payrollperiodpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='PENDING', max_length=9),
        ),
    ]
