# Generated by Django 2.2 on 2019-06-11 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190611_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='clockin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Clockin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 11, 0, 0, 0, 466528, tzinfo=utc)),
        ),
    ]
