# Generated by Django 2.2 on 2019-11-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191024_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='api.Employer')),
            ],
        ),
    ]
