# Generated by Django 2.2 on 2019-11-01 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191024_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='breaktime_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 1, 0, 0, 0, 403639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payrollperiodpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=9),
        ),
    ]
