# Generated by Django 2.2 on 2019-11-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20191101_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdeduction',
            name='employer',
        ),
        migrations.AddField(
            model_name='employer',
            name='deductions',
            field=models.ManyToManyField(to='api.PaymentDeduction'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='api.Profile')),
            ],
        ),
    ]
