# Generated by Django 2.2 on 2019-11-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20191101_0351'),
        ('api', '0038_auto_20191101_1631'),
    ]

    operations = [
    ]
