# Generated by Django 2.2 on 2019-11-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20191101_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='deductions',
        ),
        migrations.AddField(
            model_name='paymentdeduction',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='api.Employer'),
            preserve_default=False,
        ),
    ]
