# Generated by Django 2.2 on 2019-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merge_20191104_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
