# Generated by Django 2.2 on 2019-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20191106_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('FINALIZED', 'Finalized'), ('OPEN', 'Open')], default='OPEN', max_length=9),
        ),
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.ManyToManyField(blank=True, to='api.Document'),
        ),
        migrations.AddField(
            model_name='employer',
            name='documents',
            field=models.ManyToManyField(blank=True, to='api.Document'),
        ),
    ]
