# Generated by Django 2.2 on 2019-11-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20191107_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FINALIZED', 'Finalized'), ('PAID', 'Paid')], default='OPEN', max_length=9),
        ),
    ]
