# Generated by Django 2.2.4 on 2019-11-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20191108_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_city_man',
        ),
    ]
