# Generated by Django 2.2 on 2019-11-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20191108_0000'),
        ('api', '0046_auto_20191108_1358'),
    ]

    operations = [
    ]
