# Generated by Django 2.2.4 on 2019-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_merge_20191108_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='documents',
        ),
        migrations.AddField(
            model_name='employer',
            name='documents',
            field=models.ManyToManyField(blank=True, to='api.Document'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='payroll_period_starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
