# Generated by Django 2.2.4 on 2019-11-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_employeedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='item_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='stripe_bank_account_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
