# Generated by Django 2.2.4 on 2019-12-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20191202_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
