# Generated by Django 2.2.4 on 2019-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20191202_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinvite',
            name='manually_created',
            field=models.BooleanField(default=False),
        ),
    ]
