# Generated by Django 2.2.4 on 2019-11-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20191118_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='stripe_bank_account_token',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='routing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='wire_routing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
