# Generated by Django 2.2.4 on 2019-12-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_employeedocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
