# Generated by Django 2.2.4 on 2019-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20191130_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
