# Generated by Django 2.2.4 on 2019-12-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_shiftinvite_manually_created'),
        ('api', '0052_bankaccount_stripe_token'),
    ]

    operations = [
    ]
