# Generated by Django 2.2.4 on 2019-12-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_merge_20191214_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document_active',
            field=models.BooleanField(default=False),
        ),
    ]
