# Generated by Django 2.2.4 on 2019-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_employee_document_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
