# Generated by Django 2.2.6 on 2019-12-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_employee_document_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('validates_identity', models.BooleanField(default=False)),
                ('validates_employment', models.BooleanField(default=False)),
                ('is_form', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employeedocument',
            old_name='state',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='document_active',
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_verification_status',
            field=models.CharField(blank=True, choices=[('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending'), ('BEING_REVIEWED', 'Being Reviews'), ('APPROVED', 'Approved')], default='NOT_APPROVED', max_length=25),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
    ]
