# Generated by Django 2.2.6 on 2019-12-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20191217_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='public_id',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
