# Generated by Django 2.2.6 on 2019-12-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_appversion'),
        ('api', '0057_auto_20191217_2044'),
    ]

    operations = [
    ]
