# Generated by Django 2.2.6 on 2019-12-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_merge_20191217_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='name',
        ),
        migrations.AddField(
            model_name='appversion',
            name='change_log',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='appversion',
            name='force_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, max_length=1050),
        ),
        migrations.AddField(
            model_name='position',
            name='meta_description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='position',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(default=94, max_length=10, unique=True),
        ),
    ]
