# Generated by Django 2.2.4 on 2019-12-17 21:41

from django.db import migrations


def seed_data(apps, schema_editor):
    AppVersion = apps.get_model('api', 'AppVersion')
    AppVersion.objects.create(version=94)


class Migration(migrations.Migration):
    dependencies = [
        migrations.RunPython(seed_data),
    ]

    operations = [
    ]
