# Generated by Django 2.2.6 on 2019-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20191218_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
