# Generated by Django 2.2.4 on 2019-12-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20191218_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='build_number',
            field=models.IntegerField(default=94),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(default='94', max_length=10, unique=True),
        ),
    ]
