# Generated by Django 2.2.4 on 2019-12-18 18:30

from django.db import migrations


def seed_app_version(apps, schema_editor):
    AppVersion = apps.get_model('api', 'AppVersion')
    AppVersion.objects.create(version='1.1.59')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0060_auto_20191218_1827'),
    ]

    operations = [
        migrations.RunPython(seed_app_version),
    ]
