# Generated by Django 2.2.6 on 2019-12-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20191218_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='extra_withholding',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='filing_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED_JOINTLY', 'Married filing jointly'), ('MARRIED_SEPARATELY', 'Married filing separately'), ('HEAD', 'Head of household'), ('WIDOWER', 'Qualifying widow(er) with dependent child')], default='SINGLE', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_verification_status',
            field=models.CharField(blank=True, choices=[('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending'), ('BEING_REVIEWED', 'Being Reviewed'), ('APPROVED', 'Approved')], default='NOT_APPROVED', max_length=25),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
