# Generated by Django 2.2.6 on 2019-12-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20191218_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_invites',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='jobcoreinvite',
            name='employer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor')], default='ADMIN', max_length=25),
        ),
        migrations.AddField(
            model_name='shiftinvite',
            name='responded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
