# Generated by Django 2.2.4 on 2019-12-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20191218_1824'),
        ('api', '0061_auto_20191218_1830'),
    ]

    operations = [
    ]
