# Generated by Django 2.2.6 on 2019-12-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20191218_2140'),
    ]

    operations = [
    ]
