# Generated by Django 2.2.4 on 2019-12-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20191218_2140'),
        ('api', '0061_auto_20191218_1830'),
    ]

    operations = [
    ]
