# Generated by Django 2.2.6 on 2019-12-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20191220_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='automatically_closed',
            field=models.BooleanField(default=False),
        ),
    ]
