# Generated by Django 2.2.6 on 2019-12-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20191219_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=9),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=9),
        ),
    ]
