# Generated by Django 2.2.6 on 2019-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_clockin_automatically_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending'), ('BEING_REVIEWED', 'Being Reviewed'), ('DELETED', 'Deleted'), ('APPROVED', 'Approved')], default='APPROVED', max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_verification_status',
            field=models.CharField(blank=True, choices=[('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending'), ('MISSING_DOCUMENTS', 'Missing Documents'), ('BEING_REVIEWED', 'Being Reviewed'), ('APPROVED', 'Approved')], default='NOT_APPROVED', max_length=25),
        ),
    ]
