# Generated by Django 2.2.6 on 2019-12-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20191220_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
