# Generated by Django 2.2 on 2020-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_shift_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='approved_clockin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiodpayment',
            name='approved_clockout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
