# Generated by Django 2.2 on 2020-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20200103_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='latitude_in',
            field=models.DecimalField(decimal_places=11, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='latitude_out',
            field=models.DecimalField(decimal_places=11, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='longitude_in',
            field=models.DecimalField(decimal_places=11, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='longitude_out',
            field=models.DecimalField(decimal_places=11, default=0, max_digits=16),
        ),
    ]
