# Generated by Django 2.2.6 on 2020-01-31 20:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200106_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('regular_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('over_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('breaktime_minutes', models.IntegerField(blank=True, default=0)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='gross earnings')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='net earnings')),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('deduction_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.Employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payments', to='api.Employer')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payments', to='api.PayrollPeriod')),
            ],
        ),
    ]
