# Generated by Django 2.2.6 on 2020-01-29 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200106_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=100)),
                ('total_regular_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_over_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_breaktime_minutes', models.IntegerField(blank=True, default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('deductions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.Employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payments', to='api.Employer')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payments', to='api.PayrollPeriod')),
            ],
        ),
    ]
