# Generated by Django 2.2.4 on 2020-01-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200106_0251'),
        ('api', '0067_auto_20200103_2141'),
    ]

    operations = [
    ]
