# Generated by Django 2.2.6 on 2020-01-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200114_1657'),
        ('api', '0069_merge_20200117_1954'),
    ]

    operations = [
    ]
