# Generated by Django 2.2.6 on 2020-01-29 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_employeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
