# Generated by Django 2.2.6 on 2020-01-29 20:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20200129_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepayment',
            old_name='total_breaktime_minutes',
            new_name='breaktime_minutes',
        ),
        migrations.RenameField(
            model_name='employeepayment',
            old_name='total_over_time',
            new_name='over_time',
        ),
        migrations.RenameField(
            model_name='employeepayment',
            old_name='total_regular_hours',
            new_name='regular_hours',
        ),
        migrations.RenameField(
            model_name='employeepayment',
            old_name='gross_amount',
            new_name='earnings',
        ),
        migrations.RenameField(
            model_name='employeepayment',
            old_name='net_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='employeepayment',
            old_name='deductions',
            new_name='deduction_list',
        ),
        migrations.RenameField(
            model_name='employeepayment',
            old_name='total_deductions',
            new_name='deductions',
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='earnings',
            field=models.DecimalField(verbose_name='gross earnings', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='amount',
            field=models.DecimalField(verbose_name='net earnings', blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='deduction_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
