# Generated by Django 2.2.6 on 2020-01-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_merge_20200120_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='distance_in_miles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='clockin',
            name='distance_out_miles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
