# Generated by Django 2.2.6 on 2020-01-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20200120_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='distance_in_miles',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='distance_out_miles',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
