# Generated by Django 2.2.6 on 2020-02-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_employeepayment'),
        ('api', '0071_auto_20200120_1621'),
    ]

    operations = [
    ]
