# Generated by Django 2.2.6 on 2020-01-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20200129_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayment',
            name='status',
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
