# Generated by Django 2.2.8 on 2020-01-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200127_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('unique_name', models.CharField(max_length=25, unique=True)),
                ('image_url', models.TextField(blank=True, max_length=255)),
                ('feature_talent_search', models.BooleanField(default=True)),
                ('feature_payroll_report', models.BooleanField(default=True)),
                ('feature_smart_calendar', models.BooleanField(default=True)),
                ('feature_trusted_talents', models.BooleanField(default=True)),
                ('feature_ach_payments', models.BooleanField(default=True)),
                ('feature_calculate_deductions', models.BooleanField(default=True)),
                ('feature_quickbooks_integration', models.BooleanField(default=True)),
                ('feature_max_clockins', models.IntegerField(blank=True, default=999999999)),
                ('feature_max_invites', models.IntegerField(blank=True, default=9999999)),
                ('feature_max_shifts', models.IntegerField(blank=True, default=9999999)),
                ('feature_max_active_employees', models.IntegerField(blank=True, default=9999999)),
                ('feature_max_favorite_list_size', models.IntegerField(blank=True, default=9999999)),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('price_year', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('price_per_clockins', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price_per_invites', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price_per_shifts', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price_per_active_employees', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.City'),
        ),
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=25)),
                ('payment_mode', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=9)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employer')),
                ('subscription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.SubscriptionPlan')),
            ],
        ),
    ]
