# Generated by Django 2.2.8 on 2020-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200131_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='total_payments',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
