# Generated by Django 2.2.8 on 2020-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20200206_1548'),
        ('api', '0075_payrollperiod_total_payments'),
    ]

    operations = [
    ]
