# Generated by Django 2.2.8 on 2020-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20200213_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_4dig_ssn',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
