# Generated by Django 2.2.8 on 2020-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20200221_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='distance_in_miles',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='clockin',
            name='distance_out_miles',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
