# Generated by Django 2.2.8 on 2020-02-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20200225_1506'),
        ('api', '0080_auto_20200226_2201'),
    ]

    operations = [
    ]
