# Generated by Django 2.2.8 on 2020-02-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_merge_20200227_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='legal_over_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
