# Generated by Django 2.2.8 on 2020-05-21 07:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_employeepayment_legal_over_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_employers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
