# Generated by Django 2.2.8 on 2020-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_profile_other_employers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employer_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], default='ADMIN', max_length=25),
        ),
    ]
