# Generated by Django 2.2.8 on 2020-05-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20200527_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_employers',
        ),
    ]
