# Generated by Django 2.2.8 on 2020-08-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_profile_other_employers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], default='ADMIN', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users_employer', to='api.Employer')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users_profile', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='other_employers',
            field=models.ManyToManyField(blank=True, related_name='other_employers', through='api.EmployerUsers', to='api.Employer'),
        ),
    ]
