# Generated by Django 2.2.8 on 2020-08-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20200803_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcoreinvite',
            name='employer_role',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='jobcoreinvite',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPANY', 'Company Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=9),
        ),
    ]
