# Generated by Django 2.2.8 on 2020-08-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20200810_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrates',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
    ]
