# Generated by Django 2.2.8 on 2020-08-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_payrates_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='stop_receiving_invites',
            field=models.BooleanField(default=True),
        ),
    ]
