# Generated by Django 2.2.8 on 2020-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20200826_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_4dig_ssn',
            field=models.CharField(blank=True, default='0000', max_length=4),
        ),
    ]
