# Generated by Django 2.2.8 on 2020-09-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20200831_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_4dig_ssn',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
