# Generated by Django 2.2.8 on 2020-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20200924_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
