# Generated by Django 2.2.8 on 2020-10-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_shift_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='w4_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
