# Generated by Django 2.2.8 on 2020-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_employee_w4_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiodpayment',
            name='over_time',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollperiodpayment',
            name='regular_hours',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
        ),
    ]
