# Generated by Django 2.2.8 on 2020-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20201019_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
