# Generated by Django 2.2.8 on 2020-10-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_employeepayment_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayment',
            name='hourly_rate',
        ),
    ]
