# Generated by Django 2.2.8 on 2020-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_employeepayment_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='I9Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=100)),
                ('last_name', models.TextField(blank=True, max_length=100)),
                ('middle_initial', models.TextField(blank=True, max_length=100)),
                ('other_last_name', models.TextField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('apt_number', models.TextField(blank=True, max_length=100)),
                ('state', models.TextField(blank=True, max_length=100)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('zipcode', models.TextField(blank=True, max_length=100)),
                ('date_of_birth', models.TextField(blank=True, max_length=100)),
                ('social_security', models.TextField(blank=True, max_length=100)),
                ('email', models.TextField(blank=True, max_length=100)),
                ('phone', models.TextField(blank=True, max_length=100)),
                ('employee_attestation', models.CharField(blank=True, choices=[('CITIZEN', 'A citizen of the United States'), ('NON_CITIZEN', 'A noncitizen national of the United States'), ('RESIDENT', 'A lawful permanent resident'), ('ALIEN', 'An alien authorized to work')], default='CITIZEN', max_length=25)),
                ('USCIS', models.TextField(blank=True, max_length=100)),
                ('I_94', models.TextField(blank=True, max_length=100)),
                ('passport_number', models.TextField(blank=True, max_length=100)),
                ('country_issuance', models.TextField(blank=True, max_length=100)),
                ('employee_signature', models.URLField(blank=True)),
                ('date_employee_signature', models.TextField(blank=True, max_length=100)),
                ('translator', models.BooleanField(default=False)),
                ('translator_signature', models.URLField(blank=True)),
                ('date_translator_signature', models.TextField(blank=True, max_length=100)),
                ('translator_first_name', models.TextField(blank=True, max_length=100)),
                ('translator_last_name', models.TextField(blank=True, max_length=100)),
                ('translator_address', models.TextField(blank=True, max_length=100)),
                ('translator_state', models.TextField(blank=True, max_length=100)),
                ('translator_city', models.TextField(blank=True, max_length=100)),
                ('translator_zipcode', models.TextField(blank=True, max_length=100)),
                ('document_a', models.URLField(blank=True)),
                ('document_b_c', models.URLField(blank=True)),
                ('document_b_c2', models.URLField(blank=True)),
            ],
        ),
    ]
