# Generated by Django 2.2.8 on 2020-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_i9form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i9form',
            name='I_94',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='USCIS',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='apt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='country_issuance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='date_employee_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='date_translator_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='other_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='social_security',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='translator_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='translator_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='translator_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='translator_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='translator_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='translator_zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
