# Generated by Django 2.2.8 on 2020-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20201124_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='i9form',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
