# Generated by Django 2.2.8 on 2020-11-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_i9form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='document_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='document_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='i9form',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
    ]
