# Generated by Django 2.2.8 on 2020-11-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_auto_20201129_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i9form',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='i9form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.I9Form'),
        ),
    ]
