# Generated by Django 2.2.8 on 2020-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_profile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='W4Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_status', models.CharField(blank=True, choices=[('SINGLE', 'Single or married filing separately'), ('MARRIED', 'Married filing jointly'), ('HEAD_HOUSEHOLD', 'Head of household')], default='SINGLE', max_length=25)),
                ('step2a', models.BooleanField(default=False)),
                ('step2b', models.BooleanField(default=False)),
                ('step2c', models.BooleanField(default=False)),
                ('dependant', models.BooleanField(default=False)),
                ('dependant3a', models.BooleanField(default=False)),
                ('dependant3b', models.CharField(blank=True, max_length=100)),
                ('dependant3c', models.CharField(blank=True, max_length=100)),
                ('step4a', models.CharField(blank=True, max_length=100)),
                ('step4b', models.CharField(blank=True, max_length=100)),
                ('step4c', models.CharField(blank=True, max_length=100)),
                ('employee_signature', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
            ],
        ),
    ]
