# Generated by Django 2.2.8 on 2020-12-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_w4form'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='w4form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.W4Form'),
        ),
    ]
