# Generated by Django 2.2.8 on 2020-12-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_employee_w4form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='i9form',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='w4form',
        ),
        migrations.AddField(
            model_name='i9form',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
    ]
