# Generated by Django 2.2.8 on 2020-12-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20201228_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='w4form',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
    ]
