# Generated by Django 2.2.8 on 2020-12-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_w4form_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i9form',
            name='date_employee_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='date_translator_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='i9form',
            name='employee_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='w4form',
            name='employee_signature',
            field=models.TextField(blank=True),
        ),
    ]
