# Generated by Django 2.2.8 on 2021-09-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_employersubscription_stripe_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersubscription',
            name='stripe_cus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
