# Generated by Django 2.2.8 on 2021-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_employersubscription_stripe_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='total_employees',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
