# Generated by Django 2.2.8 on 2021-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_employeepayment_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayment',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='regular_hours_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='regular hours earnings'),
        ),
    ]
