# Generated by Django 2.2.8 on 2022-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employability_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
