# Generated by Django 2.2.8 on 2022-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_employee_employability_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_verification_status',
            field=models.CharField(blank=True, choices=[('NOT_APPROVED', 'Not Approved'), ('PENDING', 'Pending'), ('MISSING_DOCUMENTS', 'Missing Documents'), ('BEING_REVIEWED', 'Being Reviewed'), ('APPROVED', 'Approved')], default='BEING_REVIEWED', max_length=25),
        ),
    ]
